name: Publish Docker image

on: [push]

jobs:
  pub-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build . -t alexnicoll/go-editor
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push image
      run: docker push alexnicoll/go-editor
